eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
  # prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka      
