server:
  # port: ${PORT:${SERVER_PORT:0}}
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
